name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build
    strategy:
      matrix:
        platform: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Convert icon
      run: |
        if [ "${{ matrix.platform }}" == "windows-latest" ]; then
          magick -background transparent mvg:icon.svg icon.ico
        elif [ "${{ matrix.platform }}" == "macos-latest" ]; then
          brew install svg2png libicns
          svg2png -w 500 -h 500 -i ./icon.svg -o icon.png
          png2icns icon.icns icon.png
        fi

    - name: Install and build with PyInstaller
      run: |
        if [ "${{ matrix.platform }}" == "windows-latest" ]; then
          ICON_OPTION="--icon=icon.ico"
        elif [ "${{ matrix.platform }}" == "macos-latest" ]; then
          ICON_OPTION="--icon=icon.icns"
        else
          ICON_OPTION=""
        fi
        pip install pyinstaller
        pyinstaller --onefile $ICON_OPTION mygirlfriendisasleep.py

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: mygirlfriendisasleep-${{ matrix.platform }}
        path: dist/mygirlfriendisasleep*

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download artifacts
      uses: actions/download-artifact@v2

    - name: Extract changes for the current release from CHANGELOG.md
      id: changelog
      run: |
        CHANGELOG_CONTENT=$(awk -v version=${{ github.ref }} 'BEGIN {printmode=0; changelog=""} $0 ~ version {printmode=1} printmode {changelog=changelog"\n"$0} $0 ~ "^## " && $0 !~ version {printmode=0} END {print changelog}' CHANGELOG.md)
        echo "::set-output name=content::$CHANGELOG_CONTENT"

    - name: Create Release and Upload Artifacts
      uses: gh-release/gh-release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: ${{ steps.changelog.outputs.content }}
        draft: false
        prerelease: false
        files: |
          ./mygirlfriendisasleep-windows-latest/mygirlfriendisasleep-${{ github.ref }}.exe
          ./mygirlfriendisasleep-ubuntu-latest/mygirlfriendisasleep-${{ github.ref }}
          ./mygirlfriendisasleep-macos-latest/mygirlfriendisasleep-${{ github.ref }}
