name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  icon-conversion:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install icon-gen
      run: npm install -g icon-gen

    - name: Make icons directory
      run: mkdir icons

    - name: Generate .ico icon
      run: icon-gen -r -i icon.svg -o ./icons --ico --ico-name icon --ico-sizes 256

    - name: Generate .icns icon
      run: icon-gen -r -i icon.svg -o ./icons --icns --icns-name icon --icns-sizes 1024

    - name: Check for generated icons
      run: |
        if [ ! -f ./icons/icon.ico ]; then
          echo "icon.ico not found!"
          exit 1
        fi
        if [ ! -f ./icons/icon.icns ]; then
          echo "icon.icns not found!"
          exit 1
        fi
      shell: bash

    - name: Upload icons as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: icons
        path: ./icons
   
  build:
    name: Build
    needs: icon-conversion
    strategy:
      matrix:
        platform: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Download icon artifact
      if: matrix.platform == 'windows-latest' || matrix.platform == 'macos-latest'
      uses: actions/download-artifact@v3
      with:
        name: icons
        path: ./icons
        
    - name: Extract version from tag
      id: version
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        if [ -z "$VERSION" ]; then
          echo "Version not set!"
          exit 1
        fi
        echo "version=$VERSION" >> $GITHUB_ENV
      shell: bash
    
    - name: Install and build with PyInstaller
      run: |
        if [ "${{ matrix.platform }}" == "windows-latest" ]; then
          ICON_OPTION="--icon=./icons/icon.ico"
        elif [ "${{ matrix.platform }}" == "macos-latest" ]; then
          ICON_OPTION="--icon=./icons/icon.icns"
        else
          ICON_OPTION=""
        fi
        pip install pyinstaller
        pyinstaller --onefile $ICON_OPTION -n "mygirlfriendisasleep-${{ steps.version.output.version }}" mygirlfriendisasleep.py
      shell: bash

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: mygirlfriendisasleep-${{ matrix.platform }}
        path: dist/mygirlfriendisasleep*

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download build artifacts
      uses: actions/download-artifact@v3

    - name: Extract changes for the current release from CHANGELOG.md
      id: changelog
      run: |
        CHANGELOG_CONTENT=$(awk -v version=${{ needs.build.output.version }} 'BEGIN {printmode=0; changelog=""} $0 ~ version {printmode=1} printmode {changelog=changelog"\n"$0} $0 ~ "^## " && $0 !~ version {printmode=0} END {print changelog}' CHANGELOG.md)
        echo "changelog_content=$CHANGELOG_CONTENT" >> "$GITHUB_OUTPUT"

    - name: Create Release and Upload Artifacts
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: ${{ needs.build.output.version }}
        name: MyGirlfriendIsAsleep ${{ needs.build.output.version }}
        body: "$changelog_content"
        draft: false
        prerelease: false
        files: |
          ./mygirlfriendisasleep-windows-latest/mygirlfriendisasleep-${{ needs.build.output.version }}.exe
          ./mygirlfriendisasleep-ubuntu-latest/mygirlfriendisasleep-${{ needs.build.output.version }}
          ./mygirlfriendisasleep-macos-latest/mygirlfriendisasleep-${{ needs.build.output.version }}
