name: Build and Release

on:
  push:
    tags:
      - 'v*'
env:
  version: ${{github.ref_name}}

jobs:
  icon-conversion:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install icon-gen
      run: npm install -g icon-gen

    - name: Make icons directory
      run: mkdir icons

    - name: Generate .ico icon
      run: icon-gen -r -i icon.svg -o ./icons --ico --ico-name icon --ico-sizes 256

    - name: Generate .icns icon
      run: icon-gen -r -i icon.svg -o ./icons --icns --icns-name icon --icns-sizes 1024

    - name: Check for generated icons
      run: |
        if [ ! -f ./icons/icon.ico ]; then
          echo "icon.ico not found!"
          exit 1
        fi
        if [ ! -f ./icons/icon.icns ]; then
          echo "icon.icns not found!"
          exit 1
        fi
      shell: bash

    - name: Upload icons as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: icons
        path: ./icons
   
  build:
    name: Build
    needs: icon-conversion
    strategy:
      matrix:
        platform: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Download icon artifact
      if: matrix.platform == 'windows-latest' || matrix.platform == 'macos-latest'
      uses: actions/download-artifact@v3
      with:
        name: icons
        path: ./icons

    - name: Install and build with PyInstaller
      run: |
        if [ "${{ matrix.platform }}" == "windows-latest" ]; then
          ICON_OPTION="--icon=./icons/icon.ico"
        elif [ "${{ matrix.platform }}" == "macos-latest" ]; then
          ICON_OPTION="--icon=./icons/icon.icns"
        else
          ICON_OPTION=""
        fi
        pip install pyinstaller
        pyinstaller --onefile $ICON_OPTION -n mygirlfriendisasleep-${{ env.version }} mygirlfriendisasleep.py
      shell: bash

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: mygirlfriendisasleep-${{ matrix.platform }}
        path: dist/mygirlfriendisasleep*

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download build artifacts
      uses: actions/download-artifact@v3

    - name: Extract changes for the current release from CHANGELOG.md
      id: changelog
      run: |
        CHANGELOG_CONTENT=$(awk -v version=${{ env.version }} 'BEGIN {printmode=0; changelog=""} $0 ~ version {printmode=1} printmode {changelog=changelog"\n"$0} $0 ~ "^## " && $0 !~ version {printmode=0} END {print changelog}' CHANGELOG.md)
        ESCAPED_CHANGELOG_CONTENT=$(echo "$CHANGELOG_CONTENT" | sed 's/[\#\$\&\*\?\|\\"\<\>\;\(\)]/\\&/g')
        echo "changelog_content=$ESCAPED_CHANGELOG_CONTENT" >> "$GITHUB_OUTPUT"

    - name: Create Release and Upload Artifacts
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: ${{ env.version }}
        name: MyGirlfriendIsAsleep ${{ env.version }}
        body: "$changelog_content"
        draft: false
        prerelease: false
        files: |
          ./mygirlfriendisasleep-windows-latest/mygirlfriendisasleep-${{ env.version }}.exe
          ./mygirlfriendisasleep-ubuntu-latest/mygirlfriendisasleep-${{ env.version }}
          ./mygirlfriendisasleep-macos-latest/mygirlfriendisasleep-${{ env.version }}
